### ISSUE TITLE
Déployer l'image Docker Oxygen-CS sur le cluster Kubernetes.

### ISSUE THREAD

**Issue by DylanCorfmat** [LOG680E2/oxygen-cs-grp2-eq2#7]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DylanCorfmat** [comment]
Respecter les limites d'utilisation de CPU et de mémoire définies pour les conteneurs.

**Comment by Freddy-Loon** [comment]
duplicate

**Comment by Freddy-Loon** [comment]
duplicate
